### ISSUE TITLE
Aerial Lidar point cloud dataset

### ISSUE THREAD

**Issue by amardeepjaiman** [themmes/pointcloud-example-notebooks#1] opened 2019-02-25 09:41 UTC
Hi @themmes ,

Can i use this implementation to prepare dataset for aerial lidar bourne data which i want to use for classifying each points in the point cloud. I have around 17 millions point in each las files for around 1 sq km area. Here Max_NUM_POINTS means we are only using 4096 points from the whole point cloud for training ? cant we use all of them ?

Thanks in advance

**Comment by themmes** [comment] 2019-02-25 20:33
Hi @amardeepjaiman,

The 4096 is a limit to ensure each grid cell contains the same amount of points. Have you considered decreasing your grid size? 1x1km seems very large, it might be smart to relate this to the type of classes/objects you wish to classify.

I will look at your bugreport later this week as I do not have time to reproduce at this moment.

**Comment by amardeepjaiman** [comment] 2019-02-26 05:13
Thanks for replying Tom !!
yes ,i can reduce the grid size. So do you mean to divide the .las file in such size that they have around 4096 points in each ?

Also my classes are ground features like buildings, roads, ground, water etc. but i couldnt get your point here "it might be smart to relate this to the type of classes/objects you wish to classify." could you please explain this ?

Thanks in advance

**Comment by amardeepjaiman** [comment] 2019-02-26 05:15
Also in your source code pipeline.ipynb, i have found method compute grid size of 5 meter. is this the piece of code which is dividing the points in 5 meter grids ?

in the same file, while translating origin these 2 lines are written 

df['X'] = df.X - df.X.min()
df['Y'] = df.Y = df.Y.min()

the second line is correct or there should be - sign instead of = in df.Y=df.Y.min() ?

**Comment by themmes** [comment] 2019-02-26 07:18
PointNet computes a feature for each point and for the entire grid cell, I would say that if you choose a grid size of about 10-25m the grid cell feature becomes more distinctive. I would start with less points (because its faster) and work your way up to increase accuracy

**Comment by amardeepjaiman** [comment] 2019-02-27 06:43
Thanks !! Can i use your below code to choose grid size according to me ?

Compute grid cell identifier
In [9]:
df = dd.read_parquet('/home/tom/vision/data/training/oakland_trans')
In [10]:
grid_size = 5.0 #meters
m = morton.Morton(dimensions=2, bits=32)
In [19]:
def get_hash(point, grid_size=grid_size):
    return m.pack((point.X // grid_size), (point.Y // grid_size))
In [6]:
df['hash'] = df[['X', 'Y']].apply(get_hash, grid_size=grid_size, meta=('hash', int), axis=1)
In [ ]:
%time df.to_parquet('/home/tom/vision/data/training/oakland_hash', compression='GZIP')

The other question is related to Translate origin code , shouldnt it be df['Y'] = df.Y - df.Y.min() instead of df['Y'] = df.Y = df.Y.min() ?

Please suggest.

**Comment by themmes** [comment] 2019-02-27 07:24
Well, as you can see you have to specify grid_size as a parameter, so you could try to discover what works best for you empirically. That piece of the code is indeed meant to compute the corresponding grid cell hash for each point.

Oh, nice catch! That is indeed a typo, if you find the time feel free to make a PR.

**Comment by amardeepjaiman** [comment] 2019-02-27 09:45
Thanks !! one more thing i am having hard time to actually use train_custom.py with the pointnet environment. There are some different function definition in model.py which is not matching with the train_custom.py. Could you please share the changes done in model.py and other files for training ?

**Comment by davdmaccartney** [comment] 2019-03-05 05:30
Hi @themmes, I try to use your pointcloud-example-notebooks with Aerial LiDAR, but I get an error just after : df['hash'] = df[['X', 'Y']].apply(get_hash, grid_size=grid_size, meta=('hash', int), axis=1), when writing to the parquet:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed eval> in <module>
any ideas ?

**Comment by amardeepjaiman** [comment] 2019-03-06 09:16
Hi @davdmaccartney , I am also working on ground feature point cloud dataset collected by aerial Lidar and trying to classify each point of point cloud in different classes using semantic segment approach of PointNet. I used pipeline.ipynb file to convert point cloud data in normalized shape and I didnt get any error. But I am getting some errors while using custom_train.py file for training using the converted dataset. Do you have any idea ?

**Comment by themmes** [comment] 2019-11-08 13:56
@davdmaccartney Not sure if I resolved the above issue via email last time, if not, this issue covers it: #3

**Comment by themmes** [comment] 2019-11-08 13:57
@amardeepjaiman Please consider opening up an issue if you run into particular errors using the `custom_train.py`.

For now I am going to close this issue.

**Closed as completed by themmes** 2019-11-08 13:57 UTC
